version: "3"
services:
  db:
    image: postgres:10-alpine
    container_name: ether_database
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ether_data
      - POSTGRES_USER=ether_data
      - POSTGRES_PASSWORD=ether_data

  etherapi:
    image: etherApi:latest
    container_name: etherApi
    restart: always
    volumes:
      - ./data/db.sqlite3:/usr/src/app/db.sqlite3
    depends_on:
      - db
      - coolq
    environment:
      - POSTGRES_DB=ether_data
      - POSTGRES_USER=ether_data
      - POSTGRES_PASSWORD=ether_data
      - ENV=production
    ports:
      - "0.0.0.0:23333:8000"
    command:
      - /bin/bash
      - -c
      - |
        cd /usr/src/app
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000