version: "3"
services
  db:
    image: postgres:10-alpine
    container_name: ether-db
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ether-db
      - POSTGRES_USER=ether-db
      - POSTGRES_PASSWORD=ether-db
    ports:
      - "0.0.0.0:5432:5433"

  etherapi:
    image: etherApi:latest
    container_name: etherApi
    restart: always
    volumes:
      -  ./data/postgres:/var/lib/postgresql/data
    depends_on:
      - db
    environment:
      - POSTGRES_DB=ether-db
      - POSTGRES_USER=ether-db
      - POSTGRES_PASSWORD=ether-db
      - ENV=production
    ports:
      - "0.0.0.0:23333:8000"
    command:
      - /bin/bash
      - -c
      - |
        cd /usr/src/app
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000